-- 고객 개발 AP에서 정보를 받았다는 가정하에 초기 세팅 insert
INSERT INTO MEMBER_INFO (USER_ID, USER_NAME, REGIS_NUM) VALUES ('dani717','김다은', '123-123')
INSERT INTO MEMBER_INFO (USER_ID, USER_NAME, REGIS_NUM) VALUES ('dani717','이다은', '1234-1234')

--  인증 개발 AP에서 정보를 받았다는 가정하에 초기 세팅 insert
INSERT INTO MEMBER_INFO (IDCARD_USER_NAME, IDCARD_REGIS_NUM, IDCARD_NUM, IDCARD_REG_DAY) VALUES ('김다은','123-123', '1111', '2020-09-09')
INSERT INTO MEMBER_INFO (IDCARD_USER_NAME, IDCARD_REGIS_NUM, IDCARD_NUM, IDCARD_REG_DAY) VALUES ('이다은','123123-123123', '2222', '2020-09-10')

-- MEMBER_INFO insert 할때 같이 insert 되야 해서 초기 세팅 insert
INSERT INTO SET_ACCOUNT_PROCESS (USER_INFO_PK) VALUES (1)
INSERT INTO SET_ACCOUNT_PROCESS (USER_INFO_PK) VALUES (2)